#
# Copyright (c) 2013-2019 Vinnie Falco (vinnie dot falco at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/beast
#

language: cpp
addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
      env:
        - BEAST_LOUNGE_COVERAGE=1
        - BEAST_LOUNGE_BUILD_TYPE=Debug
      after_success:
        - tools/coverage.sh

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - *base_sources
      compiler: g++-7
      env:
        - BEAST_LOUNGE_BUILD_TYPE=Debug
        - BEAST_LOUNGE_SANITIZE=address,undefined
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - *base_sources
      compiler: g++-8
      env:
        - BEAST_LOUNGE_BUILD_TYPE=Release
        - BEAST_LOUNGE_SANITIZE=address,undefined
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: xenial
      compiler: clang++
      env:
        - BEAST_LOUNGE_BUILD_TYPE=Release
        - BEAST_LOUNGE_SANITIZE=address,undefined

install:
  - cd ..
  - $TRAVIS_BUILD_DIR/tools/get-boost.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR

script:
  - cmake -DCMAKE_TOOLCHAIN_FILE=tools/ci_toolchain.cmake -H. -Bbuild
  - make -C build all -j2
  - make -C build test ARGS="-V"

notifications:
  email:
    on_success: never
