#
# Copyright (c) 2013-2019 Vinnie Falco (vinnie dot falco at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/beast
#

sudo: false
language: cpp
addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test

compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.9
    - *base_sources
    packages:
    - g++-7
    - clang-3.9
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.9 || true"
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email:
    on_success: never
